import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "@/components/sessionProvider";
import { Toaster } from 'sonner';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <AuthProvider>
        {children}
      </AuthProvider>
      <Toaster position="top-center" />
      </body>
    </html>
  );
}
